### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by MDSilviu** [front/gutenberg-js#32]
Was this project abandoned? It's been a long time since the last update and wordpress now reached v5.8.
Can i please get a response about this project status? Thank you.

**Comment by soft4net** [comment]
Yes i'm also wondering because i can see movement in development of https://www.drupal.org/project/gutenberg, most recent update is from today (30.05.2019).
But this project is based on out of date version of Gutenberg editor according to docs v4.8. When we can expect any updated does API differs in many ways in Gutenberg 5.8? Thanks for any replies.

**Comment by eliocro** [comment]
Yes, we are currently in the process of abandoning this project.
Gutenberg has changed a lot since we started this project. Over the last year it became a lot more modular and we no longer feel the need for gutenberg-js to exist.

On our 2 main projects that used to depend on gutenberg-js, we have moved away and started using the Gutenberg packages directly. 
Please check:
https://www.drupal.org/project/gutenberg
https://github.com/front/g-editor

The latest version of g-editor is sync'd with Gutenberg 5.7 and showcases how to use the Gutenberg packages directly, though there is much room for optimisations. We moved part of the code from gutenberg-js to g-editor and Drupal Gutenberg.

**Comment by soft4net** [comment]
Wow nice finally stable release for Drupal :D This is great i really believe that Drupal version next to Layout Builder will be two main editors for this CMS! Good job! Thank you!

**Comment by Kwadz** [comment]
> On our 2 main projects that used to depend on gutenberg-js, we have moved away and started using the Gutenberg packages directly.
Please check:
https://www.drupal.org/project/gutenberg
https://github.com/front/g-editor

I think this should be mentioned in the project description.

**Comment by SofiaSousa** [comment]
@Kwadz added to readme :)
